language: java
notifications:
  email: false
  irc:
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
    - chat.freenode.net#enmasse
    use_notice: true
    skip_join: true
sudo: required
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- oraclejdk8
before_script:
- "./.travis/setup-openshift.sh /tmp/openshift"
before_install:
- npm install -g mocha
- npm install rhea debug
- ./gradlew :artemis:buildArtemisAmqpModule
script:
- "./.travis/build.sh"
after_failure:
- sudo cat /var/log/upstart/docker.log
- sudo cat /var/lib/docker/image/overlay2/repositories.json | grep ragent
- ./systemtests/scripts/print_logs.sh
after_success:
- "./.travis/push.sh"
env:
  global:
  - TAG=${TRAVIS_COMMIT::8}
  - secure: nzIvjZW1hrO6Cb4YLZyookbzysWPEN5tqI7x+REHA+kbIyVI7KRrvsv/MJDUqWlf1svrrddAHEvMY88clld0/s4UwJRx91aX6h+SDS9K3H1fJvXoCBn3JzIBN9HglCuEQhDYhX3vY5HmUerz01vYe6ZkVeVy5YdtoDaAkNCvsNfzkDwr1GJ7DnK48eZkoWg2Fd+AheDuf3waFapOzBhedPyLhrJEejDiarbR6FjqiXrcDpVYcHxWehOEkVNlL0l1sJ09VDY2dehplcBOW8SnPBi2Adi/YesDaYHb1YnKgYW2L2lw81NyFey/G4sVYviB/zJtABUY6Wyd2AQrfCyT6ZaehEEv5DUFft2YYVVxH31yiHwqypa0yVPveb+8r3C7mrPniWn/5cg1acyAgS5YzV4Uaqjzowm03730ApPjCpXLV1LJc44y2q6A2GiG/0IYgGMdmMs+jsw6oNOps0TPQgLET0roU1jqNzLialgknMuvh6X8qqjCWJTfLVG3Umm26zLqh4bolVI8Kq3hL1kYEvQPWX3EtEv3lu+j7gT4iDZcJBFJj4hbKTY+Hz8QR/EVW3qUKiFMKW1dG0FvvmkF+y3+ejuv8nraeQ1QOH5SRWVvlRLjyXjL89q4iNJWOkUYldxRU7TiG+HOKIMJcJKs8wn6XXDA6SlS06GtPYlUFFo=
  - secure: yX9wElsSnT+Rp25nojZYtjynv0xqbFS77FZ48JcCyw8SpsQ7mpbIu2Inr6C9aVm3bTUYIo7bPvLeRz6nOQEUG7B491CmeOiXumLPh/CjigJVNe+740DDz+lPKjtlr7r/N0ss71xgdgmfEXvpjOOFlefQGtbghShaZG/MDj5os8HkS9W5AYT5YCXq535Rxxt11/DKYUQJv0spZm4EEbvPuDcTnojb5PGi55Os88w6ppnoHqCzwOHievTGs1l29A29SMby245BgI5toF407+CZYPFZIVKIaJ5hrRziWPjWQdim7xaZI+gj+pu5KhG2VH2jxlSr2JV3PIfdl6TcvKED/Za5KoWYWblgcy1FwO6bc+7GA9hemM7WthWucz3ddmf1wMwQTyy4ls1XBDyxpJSoBZOOQOYaPHAw7wusK/ZfH80PvKO2AMtybuEYXg9555H0QDP/JYAF8o4W88uvQ9EzaoU/jOVT/xBc+P+nYaGbj/I43C56b0au7tISYY6npIT6Ucgpv9j0E5mHm53zc1rxeO/E4JFIEH2/1A/va3bcjOusA3iYVPbqhKXofTqPPnz913Z8rUXGee7j93zK3UFelseI3ep690nAcN/fjFl2we1sg0OnLereujJVnjmRgNsyefvEY1rUsAPgtTzFCvLc81IFqfKdmDkKbOQh7pQ2gr4=
  - secure: Av9Wu6MXBDouaXm+KGih/u116+8/4hSUDig3+tZhH9W7AiFikD3rmIN+bcxg637H46ZUqGEHfNH86qtHkGyjcwWec57f2mZAFSmXII2ct+zRGAFx4a+hlWlEN4tktzwtll33/lW2Jw4bSIxvP96AcjniJTaEpz8sFh8wfYBJSKg0frlwqLKBFdGGOTl7/DzMOWJylfN1ftNnaxHuplVIkKlIHTsVum6G6ZF05kKKvfDbwiBVI9dmYq7/3N4m57qccn8CgqUyL6lqnGe9SXW6Vuw4MSFCsS7lEIvOi0s6oqYyeagi8jPS5bsBXuK5Tgy8KiDleM5ZkpnsxO5lDvfHx8Gck8Ke3tIzlv6nj32HSwRWm8Naq9BysBe6DSN0QZNj7nQ/jWDb7A76FWY/lxRSgskkDXNItCInx+r52g358LrTSVhI/SifKCDw06mJnZLkVyS2ZzxYbs4Re+zFG1PDyRK/dnqDX7HQtI1+G0DgEmxikFz0E92MPlaa6FSdFResreLWgP4122YRUcERu600dzueActb0f2NidxMbcq/9y1lvUlmERBv2JEkJ2O3FK5DsXZ1HrqvT+kCQ0H5RRnrMqldon4joXssLANKos/h2hhULuwx53UfkGZqlq2F0jwlS9IR6crTcVdBRUkTb7+0g6cqtHs6kscW16FkSLyB8Nw=
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
  file: templates/build/enmasse-${TAG}.tgz
  on:
    tags: true
    repo: EnMasseProject/enmasse
- provider: bintray
  file: ".bintray.json"
  user: "${BINTRAY_API_USER}"
  on:
    tags: true
  key:
    secure: wFYqVs8DrJLqKrKsR1xaalhJV4P2EOo6tOAiC9LQJ6MbUabg45BKKlsvCq+w0uZkTg/mldS6NvVwFKHuvvV2RBKQKUJmbgBfrjU02WgAKwe18CsVbRuWZF2mnMbw8b9XMTFE5QtIMO+N0I4mdq5SvZwV6obvaZeDc5OK19dkANNvSPJoJx/CElUB5AKLX2lRK52t9FEHHz4FqevjQP1TVDfN8IpTIjmO6Y/icREeLWyi7C31h61wA4MBei9qxhHTfRgEYd7HUJdVK9rNaYcx3JWwXgfNRStKEuntKYI2JUwuGGf9yoAbnGNCckRDh6KkRP2NwE+8j5B/u2MRpH/xgl7kGuv+FZi3eLHGQFWx8TTEmE4uJfPM85Tt5mUbXh2HgxkWNHvuwo5HGKT6tNZ1HePdHFqonUa3Yx0a2DKQC/i7S9Rof3ywkFlzb0rVBin/k/OBGNFF7Si4ek0TYu/s7nZy5wSyViddE/1yo5NHgC3ItD/ALntwi2NQtS6bwK/fmERo2KuS/ixjjTZ+rUXTc4vkIdaNOPvrJD/y0qPNaXkeh6xDEoomoL6YkGNkxBctEjAiQTOhXg+Obev5l3yruIUSDAzm2yJQ2c1mjVeH+DK8lK7nHkb6wecv6UoI0iRUwUDOnFFsiu3mm7fFamR5v0u6b+iFA1DQNKyC89q+Dmw=
- provider: bintray
  file: ".bintray.json"
  user: "${BINTRAY_API_USER}"
  key:
    secure: wFYqVs8DrJLqKrKsR1xaalhJV4P2EOo6tOAiC9LQJ6MbUabg45BKKlsvCq+w0uZkTg/mldS6NvVwFKHuvvV2RBKQKUJmbgBfrjU02WgAKwe18CsVbRuWZF2mnMbw8b9XMTFE5QtIMO+N0I4mdq5SvZwV6obvaZeDc5OK19dkANNvSPJoJx/CElUB5AKLX2lRK52t9FEHHz4FqevjQP1TVDfN8IpTIjmO6Y/icREeLWyi7C31h61wA4MBei9qxhHTfRgEYd7HUJdVK9rNaYcx3JWwXgfNRStKEuntKYI2JUwuGGf9yoAbnGNCckRDh6KkRP2NwE+8j5B/u2MRpH/xgl7kGuv+FZi3eLHGQFWx8TTEmE4uJfPM85Tt5mUbXh2HgxkWNHvuwo5HGKT6tNZ1HePdHFqonUa3Yx0a2DKQC/i7S9Rof3ywkFlzb0rVBin/k/OBGNFF7Si4ek0TYu/s7nZy5wSyViddE/1yo5NHgC3ItD/ALntwi2NQtS6bwK/fmERo2KuS/ixjjTZ+rUXTc4vkIdaNOPvrJD/y0qPNaXkeh6xDEoomoL6YkGNkxBctEjAiQTOhXg+Obev5l3yruIUSDAzm2yJQ2c1mjVeH+DK8lK7nHkb6wecv6UoI0iRUwUDOnFFsiu3mm7fFamR5v0u6b+iFA1DQNKyC89q+Dmw=
