---
apiVersion: v1
kind: Template
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
    name: keycloak
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          name: keycloak
      spec:
        containers:
        - env:
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                key: admin.username
                name: "${KEYCLOAK_SECRET_NAME}"
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin.password
                name: "${KEYCLOAK_SECRET_NAME}"
          image: "${STANDARD_AUTHSERVICE_IMAGE}"
          livenessProbe:
            initialDelaySeconds: 120
            tcpSocket:
              port: amqps
          name: keycloak
          ports:
          - containerPort: 5671
            name: amqps
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: "/opt/jboss/keycloak/standalone/data"
            name: keycloak-persistence
          - mountPath: "/opt/jboss/keycloak/standalone/cert"
            name: "${STANDARD_AUTHSERVICE_SECRET_NAME}"
        volumes:
        - emptyDir: {}
          name: keycloak-persistence
        - name: "${STANDARD_AUTHSERVICE_SECRET_NAME}"
          secret:
            secretName: "${STANDARD_AUTHSERVICE_SECRET_NAME}"
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
    name: keycloak-controller
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          name: keycloak-controller
      spec:
        containers:
        - env:
          - name: STANDARD_AUTHSERVICE_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: admin.username
                name: "${KEYCLOAK_SECRET_NAME}"
          - name: STANDARD_AUTHSERVICE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin.password
                name: "${KEYCLOAK_SECRET_NAME}"
          image: "${KEYCLOAK_CONTROLLER_IMAGE}"
          name: keycloak-controller
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: standard-authservice
  spec:
    ports:
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: amqps
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      name: keycloak
parameters:
- description: The docker image to use for the 'standard' auth service
  name: STANDARD_AUTHSERVICE_IMAGE
  value: docker.io/enmasseproject/keycloak:latest
- description: The secret where keycloak credentials are stored
  name: KEYCLOAK_SECRET_NAME
  value: keycloak-credentials
- description: The docker image to use for the keycloak controller
  name: KEYCLOAK_CONTROLLER_IMAGE
  value: docker.io/enmasseproject/keycloak-controller:latest
- description: The secret containing the tls certificate and key
  name: STANDARD_AUTHSERVICE_SECRET_NAME
  value: standard-authservice-cert
